export const AI_PROFILES = {
  easy: {
    knockWeights: { frowny: 8, smiley: 0, blank: 1 },
    smileyPenalty: 6,
    targetWeakestWeight: 1.0,
    originEdgePenalty: 0.2,
    endEdgePenalty: 0.4,
    centerControl: 0.5,
    lookaheadDepth: 0,
    lookaheadFactor: 0.0,
    noise: 0.8,
    recallMoves: 2,
    moveFrownyPenalty: 8,
    moveSmileyPenalty: 3,
    placeCenterExp: 0.8,
    placeEdgeExp: 0.8,
    // New: protection weights
    protectFrowny: 6,
    frownyExposure: 4,
    threatEvalTopN: 3,
  },
  medium: {
    knockWeights: { frowny: 12, smiley: 0, blank: 1.5 },
    smileyPenalty: 10,
    targetWeakestWeight: 1.8,
    originEdgePenalty: 0.4,
    endEdgePenalty: 0.8,
    centerControl: 1.0,
    lookaheadDepth: 1,
    lookaheadFactor: 0.5,
    noise: 0.35,
    recallMoves: 6,
    moveFrownyPenalty: 12,
    moveSmileyPenalty: 5,
    placeCenterExp: 1.2,
    placeEdgeExp: 1.2,
    protectFrowny: 10,
    frownyExposure: 7,
    threatEvalTopN: 5,
  },
  hard: {
    knockWeights: { frowny: 16, smiley: 0, blank: 2 },
    smileyPenalty: 14,
    targetWeakestWeight: 2.4,
    originEdgePenalty: 0.8,
    endEdgePenalty: 1.2,
    centerControl: 1.6,
    lookaheadDepth: 2,
    lookaheadFactor: 0.8,
    noise: 0.1,
    recallMoves: 999,
    moveFrownyPenalty: 16,
    moveSmileyPenalty: 7,
    placeCenterExp: 1.6,
    placeEdgeExp: 1.6,
    protectFrowny: 14,
    frownyExposure: 10,
    threatEvalTopN: 8,
  },
};
